using System.Collections.Immutable;
using System.Text;
using Tombatron.Turbo.SourceGenerator.Models;

namespace Tombatron.Turbo.SourceGenerator;

/// <summary>
/// Generates C# source code containing metadata about turbo-frames for runtime lookup.
/// All methods are pure functions with no side effects.
/// </summary>
public static class MetadataGenerator
{
    /// <summary>
    /// Generates the C# source code for the TurboFrameMetadata class.
    /// </summary>
    /// <param name="razorFiles">The parsed Razor files with their frames.</param>
    /// <param name="namespace">The namespace for the generated class.</param>
    /// <returns>The generated C# source code.</returns>
    public static string GenerateMetadataSource(
        ImmutableArray<RazorFileInfo> razorFiles,
        string @namespace = "Tombatron.Turbo.Generated")
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Frozen;");
        sb.AppendLine();
        sb.AppendLine($"namespace {@namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated metadata for turbo-frame lookup at runtime.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class TurboFrameMetadata");
        sb.AppendLine("{");

        // Generate static frames dictionary
        GenerateStaticFramesDictionary(sb, razorFiles);

        sb.AppendLine();

        // Generate prefix frames dictionary
        GeneratePrefixFramesDictionary(sb, razorFiles);

        sb.AppendLine();

        // Generate lookup methods
        GenerateLookupMethods(sb);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateStaticFramesDictionary(StringBuilder sb, ImmutableArray<RazorFileInfo> razorFiles)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps static frame IDs to their sub-template view names.");
        sb.AppendLine("    /// Key: frame ID, Value: sub-template view name.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static FrozenDictionary<string, string> StaticFrames { get; } = new Dictionary<string, string>");
        sb.AppendLine("    {");

        foreach (RazorFileInfo file in razorFiles)
        {
            foreach (TurboFrame frame in file.StaticFrames)
            {
                string templateName = GetSubTemplateName(file.ViewName, frame.Id);
                sb.AppendLine($"        {{ \"{EscapeString(frame.Id)}\", \"{EscapeString(templateName)}\" }},");
            }
        }

        sb.AppendLine("    }.ToFrozenDictionary();");
    }

    private static void GeneratePrefixFramesDictionary(StringBuilder sb, ImmutableArray<RazorFileInfo> razorFiles)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Maps frame prefixes to their sub-template view names.");
        sb.AppendLine("    /// Key: prefix, Value: sub-template view name.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static FrozenDictionary<string, string> PrefixFrames { get; } = new Dictionary<string, string>");
        sb.AppendLine("    {");

        var seenPrefixes = new HashSet<string>();

        foreach (RazorFileInfo file in razorFiles)
        {
            foreach (TurboFrame frame in file.DynamicFrames.Where(f => f.HasPrefix))
            {
                // Only add each prefix once (in case multiple frames share a prefix)
                if (seenPrefixes.Add(frame.Prefix!))
                {
                    string templateName = GetPrefixTemplateName(file.ViewName, frame.Prefix!);
                    sb.AppendLine($"        {{ \"{EscapeString(frame.Prefix!)}\", \"{EscapeString(templateName)}\" }},");
                }
            }
        }

        sb.AppendLine("    }.ToFrozenDictionary();");
    }

    private static void GenerateLookupMethods(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Attempts to find a sub-template for the given frame ID.");
        sb.AppendLine("    /// First checks for an exact static match, then checks prefixes.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"frameId\">The frame ID to look up.</param>");
        sb.AppendLine("    /// <param name=\"templateName\">The sub-template view name if found.</param>");
        sb.AppendLine("    /// <returns>True if a matching template was found.</returns>");
        sb.AppendLine("    public static bool TryGetTemplate(string frameId, out string? templateName)");
        sb.AppendLine("    {");
        sb.AppendLine("        // First, try exact static match");
        sb.AppendLine("        if (StaticFrames.TryGetValue(frameId, out templateName))");
        sb.AppendLine("        {");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        // Then, try prefix match");
        sb.AppendLine("        foreach (var kvp in PrefixFrames)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (frameId.StartsWith(kvp.Key, StringComparison.Ordinal))");
        sb.AppendLine("            {");
        sb.AppendLine("                templateName = kvp.Value;");
        sb.AppendLine("                return true;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        templateName = null;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// Gets the sub-template name for a static frame.
    /// </summary>
    private static string GetSubTemplateName(string viewName, string frameId)
    {
        string sanitizedId = SanitizeIdentifier(frameId);
        return $"{viewName}_Frame_{sanitizedId}";
    }

    /// <summary>
    /// Gets the sub-template name for a prefix-based dynamic frame.
    /// </summary>
    private static string GetPrefixTemplateName(string viewName, string prefix)
    {
        string sanitizedPrefix = SanitizeIdentifier(prefix);
        return $"{viewName}_Prefix_{sanitizedPrefix}";
    }

    /// <summary>
    /// Sanitizes a string for use as part of an identifier.
    /// </summary>
    private static string SanitizeIdentifier(string input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return "Unknown";
        }

        var sb = new StringBuilder();
        foreach (char c in input)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(c);
            }
            else if (c == '_' || c == '-')
            {
                sb.Append('_');
            }
        }

        string result = sb.ToString();
        if (result.Length == 0 || char.IsDigit(result[0]))
        {
            return "_" + result;
        }

        return result;
    }

    /// <summary>
    /// Escapes a string for use in C# source code.
    /// </summary>
    private static string EscapeString(string input)
    {
        return input
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }
}
