using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Tombatron.Turbo.SourceGenerator.Models;

namespace Tombatron.Turbo.SourceGenerator;

/// <summary>
/// Source generator that discovers partial views (_*.cshtml files) and generates
/// a Partials class with compile-time metadata for each partial.
/// </summary>
[Generator]
public class PartialGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all .cshtml files provided as additional files
        IncrementalValuesProvider<AdditionalText> razorFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".cshtml", StringComparison.OrdinalIgnoreCase));

        // Parse each Razor file for partial view information
        IncrementalValuesProvider<PartialInfo?> parsedPartials = razorFiles
            .Select(static (file, cancellationToken) =>
            {
                // Check if it's a partial file before reading content
                if (!PartialParser.IsPartialFile(file.Path))
                {
                    return null;
                }

                SourceText? sourceText = file.GetText(cancellationToken);
                if (sourceText == null)
                {
                    return null;
                }

                string content = sourceText.ToString();
                return PartialParser.Parse(file.Path, content);
            })
            .Where(static info => info != null);

        // Collect all parsed partials
        IncrementalValueProvider<ImmutableArray<PartialInfo>> collectedPartials = parsedPartials
            .Select(static (info, _) => info!)
            .Collect();

        // Generate the Partials source file
        context.RegisterSourceOutput(collectedPartials, static (context, partials) =>
        {
            if (partials.Length == 0)
            {
                // Generate an empty Partials class even if no partials are found
                // This prevents compile errors if the class is referenced
                string emptySource = GenerateEmptyPartialsClass();
                context.AddSource("Partials.g.cs", SourceText.From(emptySource, Encoding.UTF8));
                return;
            }

            string source = PartialMetadataGenerator.GenerateSource(partials);
            context.AddSource("Partials.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GenerateEmptyPartialsClass()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Tombatron.Turbo.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated static class providing compile-time access to partial views.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine("/// No partial views (_*.cshtml files) were found in this project.");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine("public static class Partials");
        sb.AppendLine("{");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
