using System.Collections.Immutable;
using System.Text;
using Tombatron.Turbo.SourceGenerator.Models;

namespace Tombatron.Turbo.SourceGenerator;

/// <summary>
/// Generates C# source code for partial view metadata and the Partials class.
/// All methods are pure functions with no side effects.
/// </summary>
public static class PartialMetadataGenerator
{
    /// <summary>
    /// Generates the C# source code for the Partials class and related structs.
    /// </summary>
    /// <param name="partials">The discovered partial views.</param>
    /// <param name="namespace">The namespace for the generated class.</param>
    /// <returns>The generated C# source code.</returns>
    public static string GenerateSource(
        ImmutableArray<PartialInfo> partials,
        string @namespace = "Tombatron.Turbo.Generated")
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Tombatron.Turbo.Rendering;");
        sb.AppendLine();
        sb.AppendLine($"namespace {@namespace};");
        sb.AppendLine();

        // Generate the Partials class (using types from Tombatron.Turbo.Rendering)
        GeneratePartialsClass(sb, partials);

        return sb.ToString();
    }

    private static void GeneratePartialsClass(StringBuilder sb, ImmutableArray<PartialInfo> partials)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated static class providing compile-time access to partial views.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class Partials");
        sb.AppendLine("{");

        // Group by partial name to handle potential conflicts
        var uniquePartials = partials
            .GroupBy(p => SanitizeIdentifier(p.PartialName))
            .Select(g => g.First())
            .OrderBy(p => p.PartialName);

        foreach (var partial in uniquePartials)
        {
            string propertyName = SanitizeIdentifier(partial.PartialName);
            string viewPath = EscapeString(partial.ViewPath);
            string name = EscapeString(partial.PartialName);

            sb.AppendLine();

            if (partial.ModelTypeName != null)
            {
                // Typed partial
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// Gets the partial template for {partial.PartialName} with model type {partial.ModelTypeName}.");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine($"    public static PartialTemplate<{partial.ModelTypeName}> {propertyName} {{ get; }} =");
                sb.AppendLine($"        new(\"{viewPath}\", \"{name}\");");
            }
            else
            {
                // Untyped partial
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// Gets the partial template for {partial.PartialName}.");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine($"    public static PartialTemplate {propertyName} {{ get; }} =");
                sb.AppendLine($"        new(\"{viewPath}\", \"{name}\");");
            }
        }

        sb.AppendLine("}");
    }

    /// <summary>
    /// Sanitizes a string for use as a C# identifier.
    /// </summary>
    private static string SanitizeIdentifier(string input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return "Unknown";
        }

        var sb = new StringBuilder();
        foreach (char c in input)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(c);
            }
            else if (c == '_' || c == '-')
            {
                sb.Append('_');
            }
        }

        string result = sb.ToString();
        if (result.Length == 0 || char.IsDigit(result[0]))
        {
            return "_" + result;
        }

        return result;
    }

    /// <summary>
    /// Escapes a string for use in C# source code.
    /// </summary>
    private static string EscapeString(string input)
    {
        return input
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }
}
